# Neural network settings
embedding_size: 64
hidden_size: 128
n_lstm_layers: 1
bidirectional_lstm: False

# Training settings
max_epochs: 100
learning_rate: 2.0
sync_epochs: 10

# Privacy engine settings
enable_dp: False
secure_mode: False
delta: 0.00008
epsilon: 12.0
max_per_sample_grad_norm: 1.5

# Peer settings
port: 9998
temp_dir: ./temp
data_path: ./data/names
bootstrap_peers: []
